# Generated by Django 3.2.7 on 2021-09-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('tax', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.carddetails')),
            ],
            options={
                'db_table': 'transaction_logs',
            },
        ),
        migrations.AddIndex(
            model_name='transactionlogs',
            index=models.Index(fields=['card'], name='transaction_card_id_16d2dc_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlogs',
            index=models.Index(fields=['transaction_id'], name='transaction_transac_567f79_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlogs',
            index=models.Index(fields=['invoice_number'], name='transaction_invoice_f002df_idx'),
        ),
    ]
